# Generated by Django 4.1 on 2024-03-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_type', models.SmallIntegerField(choices=[(1, '药物生成'), (2, '药物靶点亲和度回归预测'), (3, '药物靶点亲和度分类预测'), (4, '药物反应预测'), (5, '药物属性预测'), (6, '药物路径合成规划'), (7, '药物药物反应预测')])),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.SmallIntegerField(choices=[(1, '等待中'), (2, '已开始'), (3, '已完成'), (4, '已取消'), (5, '失败')])),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
