# Generated by Django 4.1 on 2024-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_status',
            field=models.SmallIntegerField(choices=[(1, '等待中'), (2, '已开始'), (3, '已完成'), (4, '已取消'), (5, '失败')], default=1),
        ),
    ]
