# Generated by Django 4.1 on 2024-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_status',
            field=models.SmallIntegerField(choices=[(1, '等待中'), (2, '已开始'), (3, '已完成'), (4, '失败'), (5, '已取消')], default=1),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type',
            field=models.SmallIntegerField(choices=[(1, '药物生成'), (2, '药物靶点亲和度回归预测'), (3, '药物靶点亲和度分类预测'), (4, '药物反应预测'), (5, '药物属性预测'), (6, '药物合成路径规划'), (7, '药物药物反应预测')]),
        ),
    ]
