# Generated by Django 4.1 on 2024-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='predicted_finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type',
            field=models.SmallIntegerField(choices=[(1, '药物生成'), (2, '药物靶点亲和度回归预测'), (3, '药物靶点亲和度分类预测'), (4, '药物细胞系反应预测'), (5, '药物属性预测'), (6, '药物合成路径规划'), (7, '药物药物反应预测')]),
        ),
    ]
