# Generated by Django 4.1 on 2024-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_email_usermodel_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('activation_code', models.CharField(max_length=255)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
